.PHONY : all

all : 4_3_1.out 4_7_1.out 4_8_1.out 4_9_1.out 4_13_1.out

4_3_1.out : 4_3_1.c
	gcc -o 4_3_1.out 4_3_1.c

4_7_1.out : 4_7_1.c
	gcc -o 4_7_1.out 4_7_1.c

4_8_1.out : 4_8_1.c
	gcc -o 4_8_1.out 4_8_1.c

4_9_1.out : 4_9_1.c
	gcc -o 4_9_1.out 4_9_1.c

4_13_1.out : 4_13_1.c
	gcc -o 4_13_1.out 4_13_1.c

clean:
	rm -rf *.out