.PHONY : all

all : 3_6_1.out 3_6_2.out 3_9_1.out 3_14_1.out

3_6_1.out : 3_6_1.c
	gcc -o 3_6_1.out 3_6_1.c

3_6_2.out : 3_6_2.c
	gcc -o 3_6_2.out 3_6_2.c

3_9_1.out : 3_9_1.c
	gcc -o 3_9_1.out 3_9_1.c

3_14_1.out : 3_14_1.c
	gcc -o 3_14_1.out 3_14_1.c

clean :
	rm -f *.out *.o
